### ISSUE TITLE
Is your khmer wordlist licensed?

### ISSUE THREAD

**Issue by murasu** [rinabuoy/trdg#1]
Hi, I like to use your khmer word list in SBBICkm_KH.txt for an open source font proofing project called Hibizcus. The project is at https://github.com/murasu/Hibizcus.  I am not sure about the licensing as nothing is stated here. I'll be happy to add you in the acknowledgement if this wordlist is usable.  Thank you.

**Comment by rinabuoy** [comment]
Hello, I am not the creator of this dictionary. You can find the original file in this github - https://github.com/sbbic/sbbic-khmer-spelling-checker-for-ms-word/blob/master/LICENSE

**Comment by murasu** [comment]
Thank you!
